"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import NavSidebar from "./NavSideBar";
import { useEffect, useState } from "react";
import SmoothScroll from "./Smoothscroll.component";
import ScrollProgressBar from "./ScrollProgressBar";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isToggled, setToggle] = useState(false);
  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);
  return (
    <html className="!scroll-smooth" lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className={inter.className}>
        <ScrollProgressBar />
        <SmoothScroll>
          <div className="fixed z-[8000] top-0">
            <NavSidebar isToggled={isToggled} setToggle={setToggle} />
          </div>
          {scrollY < 400 && (
            <div className=" w-full fixed top-0 z-[4000] h-[100px] ">
              <NavBar isToggled={isToggled} setToggle={setToggle} />
            </div>
          )}
          <main onClick={() => setToggle(false)}> {children} </main>
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
export default RootLayout;
